version: '2'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=teste
    ports:
      - "3306:3306"
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d
      - ./db/conf/config-file.cnf:/etc/mysql/conf.d/config-file.cnf
